### ISSUE TITLE
Unable to Install on ec2 - ubuntu and IIS - Windows Server 2003

### ISSUE THREAD

**Issue by jchudzynski** [academic-colab/maslo-server#1]
Hi.
I was following the steps from the maslo-server wiki but unfortunately I stuck on accessing the admin/index.php from browser part.

I am getting the following message whenever I am trying to access the index.php on ec2. 

Fatal error: Uncaught exception 'Exception' with message 'Unable to open database: unable to open database file' in /var/www/Maslo/maslo-server/admin/util.php:33 Stack trace: #0 /var/www/Maslo/maslo-server/admin/util.php(33): SQLite3->open('../uploads/sear...') #1 /var/www/Maslo/maslo-server/admin/util.php(279): MyDB->__construct('../uploads/sear...') #2 /var/www/Maslo/maslo-server/admin/util.php(321): initSearchDB(true) #3 /var/www/Maslo/maslo-server/admin/index.php(50): initDBs() #4 {main} thrown in /var/www/Maslo/maslo-server/admin/util.php on line 33

And following message on the IIS (Which I know that it's not recommended for it)
Test Fatal error: Class 'SQLite3' not found in D:\IIS\www\Masloserver\admin\util.php on line 29 

I am not sure how to proceed. I spent quite a lot of time with that. I think the product has a lot of potential and we can't wait to get started with it! 
Any help in this matter will be appreciated.
thank you!

**Comment by cathrinw** [comment]
IIS is not supported at this point, therefore there's not much I can do to help on that platform.

On Ubuntu: It sounds like a permissions problem. Have you made sure that the appropriate 'www' user (either 'nobody' or 'www-data'  usually) has recursively full r/w/x access to the '/var/www/Maslo/maslo-server/' directory? (Optimally this directory is owned by the www user).

**Comment by jchudzynski** [comment]
Thank you for quick answer. 
I agree, it seems like permission problem.

That's my permissions for maslo-server folder.
drwxrwxrwx 5 www-data www-data 4096 2012-09-13 18:27 maslo-server

**Comment by cathrinw** [comment]
I just pushed a fix that should solve your problem. 2 weeks ago we added a publish/unpublish feature in the admin panel, which apparently broke the initial database setup. If you retrieve the most current version of the code, it should work again on ubuntu.

**Comment by jchudzynski** [comment]
It works now, thank you!
Great job!
